services:
  ra-frontend:
    env_file:
      - .env.prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: ra-frontend
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 8084:3000
    networks:
      - ra-network

networks:
  ra-network:
    external: true
