version: '3'

services:
  ra-frontend:
    env_file:
      - .env.local
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ra-frontend
    restart: always
    volumes:
      - ./:/usr/app
    ports:
      - 8084:3000
    networks:
      - local-dev

networks:
  local-dev:
    driver: bridge
